### ISSUE TITLE
broken marker images

### ISSUE THREAD

**Issue by mroswell** [eyeseast/datasette-geojson-map#26]
I don't know why I'm getting broken marker images. For some reason they point to mapbox. Which is weird, because I don't see mapbox in the code.  The file it's trying to access is:
https://a.tiles.mapbox.com/v3/marker/pin-m+7e7e7e@2x.png

visiting that yields: 
```
{
"message": "Not Authorized",
"error_detail": "Direct access not allowed"
}
```

I'm guessing there is some issue with leaflet.

<img width="1316" alt="Screen Shot 2024-01-12 at 11 28 32 PM" src="https://github.com/eyeseast/datasette-geojson-map/assets/192568/484c640f-6b1f-492b-b983-5da42d1fea00">

## ../-/databases
<img width="384" alt="Screen Shot 2024-01-12 at 11 23 45 PM" src="https://github.com/eyeseast/datasette-geojson-map/assets/192568/4cc9a529-8e67-4b7c-9f0f-3636b7083ff3">

## ../-/metadata
```
{}
```

## ../-/settings
```
{
    "default_page_size": 100,
    "max_returned_rows": 1000,
    "num_sql_threads": 3,
    "sql_time_limit_ms": 1000,
    "default_facet_size": 30,
    "facet_time_limit_ms": 200,
    "facet_suggest_time_limit_ms": 50,
    "allow_facet": true,
    "default_allow_sql": true,
    "allow_download": true,
    "suggest_facets": true,
    "default_cache_ttl": 5,
    "cache_size_kb": 0,
    "allow_csv_stream": true,
    "max_csv_mb": 100,
    "truncate_cells_html": 2048,
    "force_https_urls": false,
    "template_debug": false,
    "trace_debug": false,
    "base_url": "/"
}

```

## ../-/plugins
[
    {
        "name": "datasette-cluster-map",
        "static": true,
        "templates": false,
        "version": "0.17.2",
        "hooks": [
            "extra_body_script",
            "extra_js_urls"
        ]
    },
    {
        "name": "datasette-enrichments",
        "static": false,
        "templates": true,
        "version": "0.2",
        "hooks": [
            "actor_from_request",
            "permission_allowed",
            "register_routes",
            "table_actions"
        ]
    },
    {
        "name": "datasette-enrichments-gpt",
        "static": false,
        "templates": true,
        "version": "0.3",
        "hooks": [
            "register_enrichments"
        ]
    },
    {
        "name": "datasette-enrichments-jinja",
        "static": false,
        "templates": false,
        "version": "0.1",
        "hooks": [
            "register_enrichments"
        ]
    },
    {
        "name": "datasette-enrichments-opencage",
        "static": false,
        "templates": false,
        "version": "0.1",
        "hooks": [
            "register_enrichments"
        ]
    },
    {
        "name": "datasette-geojson",
        "static": false,
        "templates": false,
        "version": "0.4.0",
        "hooks": [
            "prepare_connection",
            "register_output_renderer"
        ]
    },
    {
        "name": "datasette-geojson-map",
        "static": true,
        "templates": false,
        "version": "0.4.0",
        "hooks": [
            "extra_body_script",
            "extra_css_urls",
            "extra_js_urls"
        ]
    },
    {
        "name": "datasette-leaflet",
        "static": true,
        "templates": false,
        "version": "0.2.2",
        "hooks": [
            "extra_body_script",
            "extra_template_vars"
        ]
    },
    {
        "name": "datasette-upload-csvs",
        "static": false,
        "templates": true,
        "version": "0.8.3",
        "hooks": [
            "menu_links",
            "permission_allowed",
            "register_routes"
        ]
    },
    {
        "name": "datasette-vega",
        "static": true,
        "templates": false,
        "version": "0.6.2",
        "hooks": [
            "extra_css_urls",
            "extra_js_urls"
        ]
    }
]

**Comment by mroswell** [comment]
Uh-oh! I tried uninstalling datasette-leaflet, and now datasette won't run., even if I try to reinstall it. 

```
% datasette install datasette-geojson-map
Traceback (most recent call last):
  File "/opt/homebrew/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/cli.py", line 17, in <module>
    from .app import (
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/app.py", line 30, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/views/database.py", line 27, in <module>
    from datasette.plugins import pm
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/plugins.py", line 27, in <module>
    pm.load_setuptools_entrypoints("datasette")
  File "/opt/homebrew/lib/python3.11/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasette_geojson_map/__init__.py", line 6, in <module>
    from datasette_leaflet import CSS_FILE
```
```
% datasette install datasette-leaflet
Traceback (most recent call last):
  File "/opt/homebrew/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/cli.py", line 17, in <module>
    from .app import (
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/app.py", line 30, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/views/database.py", line 27, in <module>
    from datasette.plugins import pm
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/plugins.py", line 27, in <module>
    pm.load_setuptools_entrypoints("datasette")
  File "/opt/homebrew/lib/python3.11/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasette_geojson_map/__init__.py", line 6, in <module>
    from datasette_leaflet import CSS_FILE
ModuleNotFoundError: No module named 'datasette_leaflet'
(venv) marjorieroswell@Marjories-2023-MacBook baltimore_gis %
```
% datasette serve .  --root

Traceback (most recent call last):
  File "/opt/homebrew/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/cli.py", line 17, in <module>
    from .app import (
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/app.py", line 30, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/views/database.py", line 27, in <module>
    from datasette.plugins import pm
  File "/opt/homebrew/lib/python3.11/site-packages/datasette/plugins.py", line 27, in <module>
    pm.load_setuptools_entrypoints("datasette")
  File "/opt/homebrew/lib/python3.11/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasette_geojson_map/__init__.py", line 6, in <module>
    from datasette_leaflet import CSS_FILE
ModuleNotFoundError: No module named 'datasette_leaflet'
(venv) marjorieroswell@Marjories-2023-MacBook baltimore_gis %

**Comment by mroswell** [comment]
I've figured out a work-around (which is to bypass the datasette-geojson-map plugin, and use the datasette-cluster-map plugin, as follows):
```
SELECT *,
    JSON_EXTRACT(geometry, '$.coordinates[1]') AS latitude,
    JSON_EXTRACT(geometry, '$.coordinates[0]') AS longitude 
FROM vacant_bldg_rehabs;
```

**Comment by Kobold** [comment]
It looks like leaflet-simplestyle's "Maki markers" depend on Mapbox icons Mapbox no longer serves 😅 . Here's a link to upstream source [1]. To address the issue, I cloned this plugin repo, made the change below to turn off Maki markers, then `setup.py install`ed my local copy of the plugin. Here's the change:

```diff
diff --git a/datasette_geojson_map/static/map.js b/datasette_geojson_map/static/map.js
index aef544d..07137ea 100644
--- a/datasette_geojson_map/static/map.js
+++ b/datasette_geojson_map/static/map.js
@@ -22,7 +22,7 @@ async function render() {
 	parent.insertBefore(container, parent.firstElementChild);

 	const map = createMap(L, container);
-	const layer = L.geoJSON(geojson, { useSimpleStyle: true, useMakiMarkers: true })
+	const layer = L.geoJSON(geojson, { useSimpleStyle: true })
 		.addTo(map)
 		.bindPopup(popup);
 	const bounds = layer.getBounds();
```

After this, markers display as expected.

[1] https://github.com/rowanwins/leaflet-simplestyle/blob/08c19856252fe644bc9ae0c97fadeca9e1f729ea/src/simplestyle.js#L80
